---
title: "DMP"
author: "Kristen Boysen"
date: "January 22, 2016"
output: html_document
---

##Data Management Plan 
#### For Climate Impacts, Environmental Informatics Project
####By Kristen Boysen and Juliano Palacios


##Types of Data

Provide a description of the data you will collect or re-use, including the file types, dataset size, number of expected files or sets, and content. Data types could include text, spreadsheets, images, 3D models, software, audio files, video files, reports, surveys, patient records, etc. Data that underlie the findings reported in a journal article or conference paper should be deposited in accordance with the policies of the publication and according to the procedures laid out in the DMP included in the proposal that led to the award on which the research is based. 

Consider the following:

What data will be generated in the research?
What data types will you be creating or capturing?
How will you capture or create the data?
If you will be using existing data, state this and include how you will obtain it.
What is the relationship between the data you are collecting and any existing data?
How will the data be processed?
What quality assurance & quality control measures will you employ?

##Data and Metadata Standards
Datasets need metadata to be usable. Think about what details (metadata) someone else would need to be able to use these files. For example, you may need a readme.txt file to explain variables, structure of the files, etc. Consider the following:

What contextual details (metadata) are needed to make the data you capture or collect meaningful?
What form will the metadata describing/documenting your data take?
How will you create or capture these details?
Which metadata standards will you use and why have you chosen them?


##Policies for access and sharing
Specify how you will share your data with others after the project is completed. Ideally, you will use an appropriate open-access discipline-specific data repository; regardless of the repository you choose, describe how you chose it. Consider these questions:

How, when, and where will you make the data available?
What resources will be needed to reuse the data? Examples include software or equipment.
What is the process for gaining access to the data?
Who are the foreseeable data users?
How should your data be cited?

##Policies for provisions for re-use, re-distribution
Describe policies surrounding the re-use of your data – the EAR division is specifically interested in how soon you will make your data available. If you will not be making the data available for re-use immediately, explain why. Remember that EAR specifies that you must make your data available no later than two years after your research is complete. If there are other policy issues regarding data access and re-use (ethical or privacy issues, for instance) elaborate on them here. Consider these questions:

When will you make the data available?
Does the original data collector/creator/principal investigator retain the right to use the data before opening it up to wider use?
Will any permission restrictions need to be placed on the data?
How long will the original data collector/creator/principal investigator retain the right to use the data before making them available for wider distribution?
Are there any embargo periods for political/commercial/patent reasons? If so, give details.
Are there ethical and privacy issues? If so, how will these be resolved?
What have you done to comply with your obligations in your IRB Protocol?
Who will hold the intellectual property rights to the data and how might this affect data access?
What and who are the intended or foreseeable uses / users of the data?


##Plans for archiving and preservation of access

What is the long-term strategy for maintaining, curating and archiving the data?
Which archive/repository/database have you identified as a place to deposit data?
What procedures does your intended long-term data storage facility have in place for preservation and backup?
How long will/should data be kept beyond the life of the project?
What data will be preserved for the long-term?
What transformations will be necessary to prepare data for preservation / data sharing?
What metadata/ documentation will be submitted alongside the data or created on deposit/ transformation in order to make the data reusable?
What related information will be deposited?