---
title: "Week 5 ggplot Group Assignment"
author: "Kristen Boysen, Jennifer Kidson & Juliano Palacios"
date: "February 7, 2016"
output: html_document
---

## Part One: Plot based on tree thinning dataset
For start year 1950, plot LAI vs transpiration in 4 different months.
```{r thin}
library(readr)
library(dplyr)
library(tidyr)
library(ggplot2)
library(gridExtra)

thin = read_csv("./data/thinning.csv")        # read in thin data
 
thin %>%
  filter(startyear == 1950 & month == 3) %>%  # filter by startyear and month (March)
  ggplot(aes(x=lai, y=trans)) +               # plot transpiration against lai
  geom_point(color = "green") +               # set color
  labs(x="Leaf Area Index (LAI)", y="Transpiration") +          # set labels
  theme(axis.line = element_line(colour = "black"), # Cleas the plot in background (j.p.)
                                                                                                       panel.grid.major = element_blank(),
                                                                                                       panel.grid.minor = element_blank(),
                                                                                                       panel.border = element_blank(),
                                                                                                       panel.background = element_blank()) +
  ggtitle("March")-> p1                       # set title and create variable for plot

thin %>%
  filter(startyear == 1950 & month == 6) %>%  # June
  ggplot(aes(x=lai, y=trans)) +
  geom_point(color = "yellow") +
  labs(x="Leaf Area Index (LAI)", y="Transpiration") +          # set labels
  theme(axis.line = element_line(colour = "black"), # Cleas the plot in background (j.p.)
                                                                                                       panel.grid.major = element_blank(),
                                                                                                       panel.grid.minor = element_blank(),
                                                                                                       panel.border = element_blank(),
                                                                                                       panel.background = element_blank()) +
  ggtitle("June") -> p2

thin %>%
  filter(startyear == 1950 & month == 9) %>%  # September
  ggplot(aes(x=lai, y=trans)) +
  geom_point(color = "orange") +
  labs(x="Leaf Area Index (LAI)", y="Transpiration") +
  theme(axis.line = element_line(colour = "black"), # Cleas the plot in background (j.p.)
                                                                                                       panel.grid.major = element_blank(),
                                                                                                       panel.grid.minor = element_blank(),
                                                                                                       panel.border = element_blank(),
                                                                                                       panel.background = element_blank()) +
    ggtitle("September") -> p3

thin %>%
  filter(startyear == 1950 & month == 12) %>% # December
  ggplot(aes(x=lai, y=trans)) +
  geom_point(color = "blue") +
  labs(x="Leaf Area Index (LAI)", y="Transpiration") +
  theme(axis.line = element_line(colour = "black"), # Cleas the plot in background (j.p.)
                                                                                                       panel.grid.major = element_blank(),
                                                                                                       panel.grid.minor = element_blank(),
                                                                                                       panel.border = element_blank(),
                                                                                                       panel.background = element_blank()) +
    ggtitle("December")-> p4

grid.arrange(p1,p2,p3,p4, top="Monthly Transpiration")     # arrange the 4 plots in a grid, with title
```

##Part Two: create plot using landing and temp data
```{r part two}
Octo <- read.csv("./Data/OctoLanding.csv")
test<- Octo %>% 
  gather("fishery", "catch", 2:4) %>% 
  filter(fishery!="Total.Landings")

octo_plot<- ggplot(test, aes(x=Year, y=catch)) +
  geom_point(aes(color=fishery, size=ONI)) +
  theme_classic() +
  ggtitle("Octopus Landings from 1980-2014") +
  labs(x="Year", y="Octopus landings (tons)") +
  theme(legend.position = "bottom")

octo_plot
```

